// import type { Metadata } from "next";
// import "./globals.css";
// import GlamzHead from "@/components/CustomHead";
// import BodyScripts from "@/components/BodyScripts";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html data-wf-domain="glamz-template.webflow.io"
//     data-wf-page="686f439ee34b78f814ae2df2"
//     data-wf-site="686f439ee34b78f814ae2de2"
//     lang="en">
//       <GlamzHead />
//       <body
      
//       >
//         {children}
//         <BodyScripts />
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import "./globals.css";
import GlamzHead from "@/components/CustomHead";
import Script from "next/script";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import WebflowInit from "@/components/WebflowInit";
import WebflowPageId from "@/components/WebflowPageId";
import { CartProvider } from "@/context/CartContext";


export const metadata: Metadata = {
  title: "PurCurie",
  description: "Pure Care For Skin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-wf-domain="glamz-template.webflow.io"
      // data-wf-page="686f439ee34b78f814ae2df2"
      data-wf-site="686f439ee34b78f814ae2de2"
    >
      {/* ------------------------- */}
      {/*         HEAD AREA          */}
      {/* ------------------------- */}
      <head>
        <GlamzHead />

        {/* Webflow Touch Detection */}
        <Script id="modernizr-touch" strategy="beforeInteractive">
          {`
            !(function (o, c) {
              var n = c.documentElement,
                t = " w-mod-";
              n.className += t + "js",
                ("ontouchstart" in o ||
                  (o.DocumentTouch && c instanceof DocumentTouch)) &&
                  (n.className += t + "touch");
            })(window, document);
          `}
        </Script>

        {/* Webflow Currency Settings */}
        <Script id="webflow-currency" strategy="beforeInteractive">
          {`
            window.__WEBFLOW_CURRENCY_SETTINGS = {
              currencyCode: "USD",
              symbol: "$",
              decimal: ".",
              fractionDigits: 2,
              group: ",",
              template:
                '{{wf {"path":"symbol","type":"PlainText"} }} {{wf {"path":"amount","type":"CommercePrice"} }} {{wf {"path":"currencyCode","type":"PlainText"} }}',
              hideDecimalForWholeNumbers: false,
            };
          `}
        </Script>
      </head>

      {/* ------------------------- */}
      {/*         BODY AREA         */}
      {/* ------------------------- */}
      <body>
        <WebflowPageId />
        <WebflowInit />
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
        <Footer />

        {/* jQuery (Required by Webflow) */}
        <Script
          src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=686f439ee34b78f814ae2de2"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
        />

        {/* Webflow Core Scripts */}
        <Script
          src="https://cdn.prod.website-files.com/686f439ee34b78f814ae2de2/js/webflow.schunk.74913c4b4b4ccfa6.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cdn.prod.website-files.com/686f439ee34b78f814ae2de2/js/webflow.schunk.b3e18e1a6e478bb6.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cdn.prod.website-files.com/686f439ee34b78f814ae2de2/js/webflow.8a267672.347e9cb06ba68506.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
